#!/usr/bin/env node
'use strict';

// Assembles the static HTML pages from src/*.html by injecting the shared
// header and footer from partials/*.html. Run with: node build.js
//
// To edit page content, edit files under src/. To edit the header or
// footer, edit files under partials/ (they apply to every page).
// Never edit the generated *.html files at the repo root directly —
// running this script again will overwrite them.

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const PARTIALS_DIR = path.join(ROOT, 'partials');
const SRC_DIR = path.join(ROOT, 'src');

const pages = [
  {
    src: 'index.html',
    out: 'index.html',
    vars: { HOME: '', BRAND_HREF: '#', KATSUDO_ACTIVE: '' },
  },
  {
    src: 'katsudo.html',
    out: 'katsudo.html',
    vars: { HOME: 'index.html', BRAND_HREF: 'index.html', KATSUDO_ACTIVE: ' class="active"' },
  },
];

function readPartial(name) {
  return fs.readFileSync(path.join(PARTIALS_DIR, `${name}.html`), 'utf8');
}

function applyVars(template, vars) {
  return template.replace(/\{\{(\w+)\}\}/g, (match, key) => {
    if (!(key in vars)) throw new Error(`Missing template var "${key}" for ${match}`);
    return vars[key];
  });
}

function insertOnce(html, marker, replacement, pageName) {
  if (!html.includes(marker)) {
    throw new Error(`${pageName}: missing "${marker}"`);
  }
  return html.replace(marker, replacement);
}

for (const page of pages) {
  let html = fs.readFileSync(path.join(SRC_DIR, page.src), 'utf8');

  const header = applyVars(readPartial('header'), page.vars);
  const footer = applyVars(readPartial('footer'), page.vars);

  html = insertOnce(html, '<!-- INCLUDE:HEADER -->', header.trimEnd(), page.src);
  html = insertOnce(html, '<!-- INCLUDE:FOOTER -->', footer.trimEnd(), page.src);

  html = html.replace(
    '<!DOCTYPE html>',
    '<!DOCTYPE html>\n<!-- AUTO-GENERATED by build.js. Do not edit this file directly:\n     edit src/' + page.src + ' and partials/*.html, then run `node build.js`. -->'
  );

  fs.writeFileSync(path.join(ROOT, page.out), html, 'utf8');
  console.log(`Built ${page.out}`);
}
